### ISSUE TITLE
add support for ``--derep_prefix`` when we support vsearch 2.1.1

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-vsearch#24]
[A `vsearch` bug](https://github.com/torognes/vsearch/issues/270) was fixed related to this functionality, so we should be able to add this as an option to `dereplicate_sequences`, except that we're currently installing `vsearch` 2.0.3. Version 2.1.1 contains the fix.

**Comment by thermokarst** [comment]
The 2.0.3 version pin appears to be coming from the [upstream `deblur`](https://github.com/biocore/conda-recipes/blob/master/recipes/deblur/meta.yaml) package; we don't appear to be pinning anywhere in the QIIME 2 org on Github.

**Comment by wasade** [comment]
I'm working on biocore/deblur#158 but I cannot find a conda installable `vsearch==2.1.1`. @gregcaporaso, were you installing from an existing repository or by source? I looked at `biocore`, `bioconda` and `qiime2`. However, it seems that `Deblur` works with `vsearch==2.5.0` so it may just be quite insensitive to the version. Verifying right now.

**Comment by gregcaporaso** [comment]
Hmm, I may have installed from source. I don't think there should be any issue with using 2.5.0 though (if that one is on conda) - as far as I know, the other plugins that use vsearch don't have a version pinned. It'd be ideal to just bump to the most recent version.

**Comment by wasade** [comment]
Excellent. We seem green on `2.5.0` with `Deblur`, and it is in `bioconda`, should we push forward with that?

**Comment by jairideout** [comment]
:+1: for obtaining vsearch 2.5.0 from `bioconda`.  Can you remove the version pin entirely from the `Deblur` recipe, or set a minimum version, so that we can keep up-to-date with vsearch releases moving forward?

**Comment by jairideout** [comment]
q2-vsearch now relies on vsearch >=2.5.0 so this issue is no longer blocked (fixed in #27).

**Comment by gregcaporaso** [comment]
I can do this for 2017.11.

**Comment by colinbrislawn** [comment]
I can add support for --derep_prefix
Thanks for building the list of **good first issues**!

**Comment by thermokarst** [comment]
Thanks @colinbrislawn - the PR freeze started last week for 2018.4, so I don't think this will be able to make it into this release, but we can certainly add it into 2018.6 - does that work for you?

**Comment by colinbrislawn** [comment]
Yep. 2018.6 (June) gives me plenty of time to get this right.

I do most of my analysis in R, so I'll be leaning the APIs for q2_types and unit testing as I go.
