### ISSUE TITLE
Set –fasta_width 0 on relevant actions

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-vsearch#48]
**Comments**
This will ensure that sequences aren't split to a new line at 80 characters.

**References**
This recently [came up on the forum](https://forum.qiime2.org/t/possible-to-set-fasta-width-0-for-consistency-with-other-plugins/3204?u=thermokarst).

**Comment by colinbrislawn** [comment]
Should we add this separately to every q2-vsearch function or perhaps add this to the top level [run_command()](https://github.com/qiime2/q2-vsearch/blob/master/q2_vsearch/_cluster_features.py#L25) function that calls vsearch?

**Comment by colinbrislawn** [comment]
The forum user suggested that the line wrapping format could be 
>inherited from the input .qza.

Now that's a great idea that is above my pay grade!

But if Qiime2 has a standard for fasta line wrapping, I can submit a PR that makes vsearch adhere to this standard.

**Comment by colinbrislawn** [comment]
On the [forums](https://forum.qiime2.org/t/where-does-hashid-get-assigned-in-dada2-deblur-and-vsearch/7738/11), @ebolyen  suggested:
>QIIME 2 has to handle either situation, so it doesn’t ultimately matter, but fixed-width fasta files are harder to parse and manipulate with unix tools, and just add extra bytes to the file for no reason.
I’m pretty sure line-wrapping has been available in terminals since the VT100, so in my personal opinion, fixed-width fasta is an abomination 😃 

So that's a vote for always outputting unwrapped fasta files. So could we simply add it to the top level run_command() function that calls vsearch? @gregcaporaso Is this clever or an antipattern?

**Comment by colinbrislawn** [comment]
Can I get some specific advice about where to add the `--fasta_width 0` flag to the command?

Option 1. Expose this as a new option to every vsearch command.
Option 2. Add this as a hardcoded call to each vsearch call, like we do for [qmask](https://github.com/qiime2/q2-vsearch/blob/master/q2_vsearch/_cluster_features.py#L190)
`'--qmask', 'none',  # ensures no lowercase DNA chars`
Option 3. Hack this into the top level [run_command](https://github.com/qiime2/q2-vsearch/blob/master/q2_vsearch/_cluster_features.py#L25) for vsearch.

I like **Option 2**, and I would like to get some feedback before I start off on the wrong path.

**Comment by ebolyen** [comment]
I think option 3 sounds good, and doesn't seem like too much of a hack to me, there's nothing very special about `run_command`, although if there are ever vsearch commands which don't support the flag, then it becomes an annoying bit of coupling. Perhaps `run_command` could have a default flag which can disable this (for internal use only)?

I don't think option 1 is super necessary (I still agree with myself as quoted :wink:  )

**Comment by colinbrislawn** [comment]
Looks like we will have to go with option 2, as some vsearch commands that output fasta files, including `uchime_denovo`, don't support the flag. 🤷‍♀ 🤷‍♂ 
Or...
Option 4: I could pass `run_command(cmd, verbose=True, unwrap_fasta=False)` for the commands that can't handle the flag.

For my own notes: valid options for various commands: https://github.com/torognes/vsearch/blob/master/src/vsearch.cc

**Comment by torognes** [comment]
The option should be valid for all vsearch commands that output fasta files. It must be a bug in vsearch if it is not valid for uchime_denovo. I will look into it soon.

**Comment by torognes** [comment]
As far as I can see `--fasta_width` is a valid option to `uchime_denovo` and all other options that write FASTA files, at least in the latest version. So I do not understand why you got an error. Do you know which version that was, @colinbrislawn?

**Comment by colinbrislawn** [comment]
>2.7.0

🙀 
I'll bump it and see what happens.

**Comment by thermokarst** [comment]
@colinbrislawn, you will have to test that locally --- travis will test off of the last-published dev env, which still has 2.7.0 in it (its a bit of a chicken-and-egg issue).

**Comment by colinbrislawn** [comment]
What can we do to test this out before the next release? I hope this PR is ready to go, but I'm not sure how best to test and any advice is appreciated.

**Comment by thermokarst** [comment]
On mobile right now, but the gist is to use conda to install this version of vsearch in a qiime 2 dev env. This might require a bit of finesse, since a few other plug-ins have a hard pin on vsearch. If you get stuck ping here again and I can try and troubleshoot with you.

**Comment by colinbrislawn** [comment]
Got it.
I'm up to try this, but I'm a little too busy right now. Once vsearch is updated globally for qiime 2, hopefully this PR can be easily resolved.
