### ISSUE TITLE
merge fastq_stats_* visualizers into a single action

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-vsearch#70]
**Improvement Description**
Now that we have a brand-new unified view type for SE and PE fastq formats, fastq_stats_single and fastq_stats_paired could be merged into a single action. See:
https://github.com/qiime2/q2-types/pull/245
and here for an open PR where this unified view type is utilized:
https://github.com/qiime2/q2-quality-control/pull/52

**Current Behavior**
fastq_stats_single and fastq_stats_paired exist as separate visualizers. I am excited for these new visualizers! We have an opportunity to merge these into one before they area released to make use more straightforward.

**Proposed Behavior**
Merge these visualizers into one `fastq_stats` visualizer. This can probably be done by:
1. changing the view type [here](https://github.com/qiime2/q2-vsearch/blob/f410ed0c78e2d7de353dd13980b9119bdad2f4cf/q2_vsearch/_stats.py#L139) to `CasavaOneEightSingleLanePerSampleDirFmt` (that format has a new `manifest` property so afaik [this line](https://github.com/qiime2/q2-vsearch/blob/f410ed0c78e2d7de353dd13980b9119bdad2f4cf/q2_vsearch/_stats.py#L79) should still work but needs testing)
2. instead of [this if statement](https://github.com/qiime2/q2-vsearch/blob/f410ed0c78e2d7de353dd13980b9119bdad2f4cf/q2_vsearch/_stats.py#L84) you could then just check if the manifest has a `reverse` column.
3. in `plugin_setup.py` you would register a union type as the input type. E.g., instead of specifying `SampleData[PairedEndSequencesWithQuality]` as seen [here](https://github.com/qiime2/q2-vsearch/blob/f410ed0c78e2d7de353dd13980b9119bdad2f4cf/q2_vsearch/plugin_setup.py#L439) you would do `SampleData[SequencesWithQuality | PairedEndSequencesWithQuality]`

Then just cleaning up the docs, tests etc to use the unified action. (I may be missing a few other steps, but the above should be the gist of the main changes I think)

**Comment by angrybee** [comment]
I took a look, it works nicely but the unittests have to be rewritten. I will open a PR this week.
